packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@types/node": ^25.9.3
  typescript: ^6.0.3
allowBuilds:
  esbuild: true
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260613.1'
